# Configuração para servidor com scraper integrado
app = "projeto-analisador-betesporte"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile.scraper"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = "512mb"  # Mais memória para Puppeteer
  cpu_kind = "shared"
  cpus = 1
